language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
env:
  global:
    - secure: t0WkQNscJXXHIAyzBQioDFXqVrAwuBYYWgQegj3ukW77axplgPKAHtH2k6sOLkrb7f91P/28bG7r47tgnGlqWuPuMIUkwl9K6l8hChvv9w9i0e/vcI33G8kOrbj4UPYgTx0HFd/F9tEAoc/RcvkgDvlJF4nxwrOAaDqkwxcKzQovi8GDMT8f0i0HTDmZQ4/wrhRf/nqmjNr0iLGN73NLws75DaWMHWxnyen101LEGx60LrvF2C5kmQ85R2lhkpJJvGbc3nBZoLC8P1jXVuZSv/Q9ww0kxGg8s/FHSB3AeFNXGvFbHNezKI7Z2lXrhOncTDATkYgwrcx2qRc32H0KgKowlAgCMmv+lDkHVDS8EssvvtMGEZ4SLSa4cVUmS9hVNlw6Nit9x5n/VIId2r28zUm94JciTCaeFsnK6War5n1E71naxT2ksAVkDlvKwSo9GrpMQtd9w7LArC7Dg34MTzZb4hS4X7zpwT5KBwvBlY+7dSlrfw49Kv7EWSKko6q6fHcHX8FuPVMkKAcnMQ9m1zwbbOfTsAgcf8fzFuTnqzGjXfqbT6tpfWhUsG9nnFHK5NN/rWKnWLp2zJPM1kskwbg6YShGVeFgvkVrDAD9yGt65FTwF/hL4Aai2pNNo6ieP0ZKH/ZV/0DuFfcwkcVc8kgMlWCyFUaE0MsKKXk2PuA=
    - secure: LXGsQzdtEnZLWc1Yg0it2Qrk9Gjn3xQ5Ls5k/JV5FqvkKiLQish9iFkpcoMenmW8tUkd44mDbka7Ue2gGeTcshNMOpDJ+idwZ9NJiP+Lzdkkj1PWtBVflHwEg+/a0OB7FTEG2tLkGa7Poz7UV0+VYojfftJUOwrabz0ZAHeOy7Pvyp9yFPxGxprQivdJxquBtuvmrTJWh8cUBQKbspGtT2kdVnEawbdukGEvRpEOFQ1CPOFBgz2etfECNUTnFsX3FkSgmALFh6XlHjEXr+oNSc8iDWvmfppOsX+JHOjZXMdXWzl434LmH3MInzTXWWgaOXlgoZzPkisiNTojYZi7/TjKZBHjm5NfD1IP6dZCSJDJB2gCZCMPSSEhVmALZ08CWj8SrmnWpxqSvGgLYcEBycuYQmLNZdqaPdjvi+bV/NEsHWwjYXtvUkxeqU5kjb+WQu1NqrMQwnhtKrv83TFrq9EOaUZ6LKY/Q0oTzHYWZaTpMUDSES8Z1/50GMR0QlYYefJUX+DRcKZNSiaVdbbawgbS6wnuAX8lUkPXaZ4ZmMWkHBnFijKVTn6KzawipD4dcMMBZnRLoAnf9gNHrwtrQPJp7XCbBZgd1Qov/bR769+vfZV3ujrtZYLDpX0MLYOj0FgIf8mR565jSUaJ9jr4IPC4JS+0ah8Rzdnb6pPkhUE=
    - secure: nWsjqPcd9GKu7z5YS8PDAcVJwbLVUbLtkcByEaC7nB0n7XsXYfKQ9bhYBA8wruOGSvbtegaBrWtvd7ge1fodxmJpsYe4bom1j5CsvLAO+74mueph+fV6F3OgrV04NYDyAKKTpBhlgFSv6GCfvLGGuJ81bwLHDcZxcUh49ra/MCbav0Cz+16Rds25+n9YzyP/k7nQVHqCTjkZgY2hQhg8PgsWTHMGsANP/jEQ2w+SSjZdeutULN8bDlqI0hVavoYHHhMJ6tepONVkIJZaRy8osVaz0TvpSGmuAlQN4LSvoaPWOFDeQw1imTeMLW1YIJn+/gEizsw3ORa982qnqoZBJCnFmnBSQFLrfVuDzh+9Na9+FFkyMmF8rZrxzG1coUgVAE5kHN6XcdvzocgUTDAYaw+feYx29nouRTjiIYR+IsbMLZ/dQ9IavSd+s+UzTpibq04As64V485/PkRcdvsSlj4+oDjp6jCmB0BlfIqIm9mpIVeTc/S4SJoTdZVRK1L7Q/jRJHkQx42DqjXUjNmt4oXN6xzl0N79eM4MWpNnNtinPGULA8FwPTrRgExT9nRqD9xQpV6On6Idy2w61K7QlgNGE8uhJDiU8nS1BIrIXjCiNFO1m3zJ8FDspZtvrm+mrV8PDV8EUzYmH/fGkIH+sxkw0HWc3KAzL1cQZvHdTLY=
    - secure: Dvq5woGMofvLJY2dXZj2uO1u2tm0zUiYUsYDGQMELcgIj+DrSIdRa96O76bPF5+OwAL7OvQf23rUIs8EdrEDBzOgOdhEjR0FrBj44NpyhXGKwVYvsw8bd2z58lvxDQk7/lAxZ7RFWBMHF9Yg6332utBT783ZrdFBASCzn0zjG/LgynR7Lt7xu3lHNQ2llcDdyQGdfsyXr8WFN7hIt2eflVLMYwD6q8Gxcc/iq2aMdTBPhwa4QCcobKrYy+cQyl8b60Uwshgdl0HlXoGcZy0pgLVBHq8AnFkGmP6zpeWKH0ovP9c9vtlZB3QdnwTNuGsb0VqMfiFrNQvhYNAy7Kp7VhWLT8wmDOeNPyZOsClneqaEeXLaAS5HW/mtuRzFyslRJ01qCBgOcL1W/x2V5M7UTqTqYF67JE8Ra7b5U7sStiucEcUmSXgWJLzJtE7ySOd9ho8CHOMLqSIqi8lcfozwiXBh1uFx3bYuwiblla+Ob0pTxLtxcBRsxQAjmpFe3Ijs8uo/KVHuwfY4CVZ1nCi5X9Up+cL9sh2eAJ+bb4WPf6LGwNBo+Ay7r20+xv6YHdPSl9QDGBq6kKUimnObujdCz8M8oxIpAGZDeEDalxhGCxtkhmHYKmLF/D0NT3TMACA8OzwK72t4JYjG3k26xyLs1pqVI8faGnNpFECuqf7hf1c=
    - secure: dhfeBa1/L/Tf+2xUrQgKZvKlGYdb+wtOBPoDZK8dBaxMdw5eO80gwjjlGK6aujQnXGEpVIHNNpyoDC5+PimOtoCQhNgFhLpHtZm04K3gBtn/NoT9wQZHUQ78UwUrEqZmky2bU2zw6e7qE7HZdPuOEItrontybv1Eh3zrYD1eaVUHUZbBL7OLKS+4bIuhoDNIJ8ctrn/kmkX2ao1GxIU/PsfwjPPoMEb2Jcm6/5+cgUb0lZLFhitrwLYciXDTh3+DZDlTvL8qHbHNKH18cvjRAaCdEUZ+8YVzeWkGgjh8/JEuftHOEtLjE0vkKftpIF2RCc9kUHgNPmYoKUWS3PiZsuJnn1Nm2ieBiyfhBybMxBKnmiROAdGLTk3AB1b51EAM7q8pM4set7zQkwVa1o4ckH2gVrs1CmarPByFXuBv5K1tO1O7QRbcHIdVYdgnOctVIbfrp1WjM06ptD60yn9A7udUhAgfFNXQ314bFa1QZ/sqIno08c4SODd33iUTt+Hb+xz32WB6cLgIpyXtfl22X+38f3MEBqD/MWe4ZiGcAnd9BT6HpUUXs54rqfdKStOENepMt9/1k2NAaHPfI1/CXrvDFbNaWQsyp5mESlTweMOSUStceB9pvmvGKlNt94kY4F+Kwa7HXLAegahT9pykSVuLe6wajBtlsHUbvg4KXi0=
addons:
  ssh_known_hosts:
    - ec2-3-124-206-1.eu-central-1.compute.amazonaws.com
    - ec2-3-120-98-15.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=customer-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-3-124-206-1.eu-central-1.compute.amazonaws.com
    'bash launch_build.sh'
  on:
    branch: master
