language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
env:
  global:
    - secure: e8NhbR65N+Mr9kulf9qtklIuNNnyoiHQYw0EU42dv7XPI48q0/zHF+nXhaAxskQGx2JjVTacGdcoGEEm6hhcC7SMabCXv0o1I66DkpWoMyp06hO0WVS394z5YHx+n7CFgw7n1fGAoFpSuXPqv3rpkC3eoF3Td6Z6rBUd7fNRrczxsLIh8avxQyU6U5QCJmXsWrA9zGgBahdHbIj3u8ACS24bflbIF519e0XWZvSjMrQLo5KRpR99skhd7Q8GspV3vppJWXtgfXTc3H0DIn+4YavsLu4HzBNx3FOcgMREyh+j1MVyOxKjOPzZUquMJImwTnaQbU9lDSgjvw6ZfeHK8d4zi/AT6do7a/J6tkh2baZ5iHLY7vHs1+wcphNwrm4uBYmB9TTYog3JR2vEqm3I4CJt5Pz2tF1lKiujIwelgB689+4RPmuf+eGpsGzEKK9JvfYhj3q4qtAlxvHiXJ3LH5/WH5QyfManAkUb5TyKwEzI0ZTuvWpZH8JXgeaLzOWGGhbA2bLK9+nxkqrRzAriq9m1pERom/87MKcmK0nAPwuIzUUPq+l1jWwbO9uBnJyGsT74w97ALCCqyrPSmq8E4tyEt5m0F7bG9wE0P9VVyQqEQQBoaP3ehDWZ/e8GDy7EbUVLua9iqpDTDgwHsFYCQpWQiu0+3URytG0vFhaU1TE=
    - secure: Ak4wDweI/vabGsFrO7BDybbqIZuRUJ5gNNLIKq3IN8QQwUbznpftwkMHKGK7/CnTKTKyCPg6cNAXzDYb/roFt1k/eVkqOtY0xqPH0x9dw2HDgYG2vtYSGhgAiXVWJ6p/wVp9Mec8Mk9u/uebeeBaDSEraI8C9NHrzeSMui44BVZ0uSQOob6tUsXvMSVW29kXNwfKw/7W+vXVwRXVzs2HTpN1F3fHoqtSxCsgtHw8bzGX3hUqkF3lmjE3XV6YoFGrF8wbbi4leOPD4vKHWj3S8x5haNmrIbf1aooesqvrVuwCVNabXRnTXxBuQAOdYiNPAzQ/eKMHLbB17eT8VbuOkwu1LX/yRntSzLiVtOutEwLdQPX9NxrcklA8Yi7zX5nMB6R3sfo7fMp6C5xFSr5BLM+C74LdoJfFs3LHXVGxOpUo4jcXJZS+K1blxuhvKQgpBlzroNq7jINiAdCoUHI9+C6XtoQQtws5CFQytt6hpgocLsuB2lncZ8mlrbChA7ABjE7r83TwgRbjjC9pZ7ZfnA4b1VYwElbgvnCQ7rxgcvijCQio69TTeQdPv6SgRFBsNzIhiQBk+uZJnyLEHZC1XXQaSVVpE/G2EIGaO0a2GwaARHLBTbIrN4reP+Fpo9lyl/5eJk2cnqHlxLz2xEexO0pd7EfHlSniP2PFI+0REAE=
    - secure: XARXLxD9C0jf8Wjo0XRJWaY9CdPmJAMFn4L1IZoku9p2EKB5WHuZXHgSTZ4QV5Zm4CeoQIT1iUpg4Gi7w3K5BxtCe5bMZh1NGECpaCFp7xMCXRqbz7TnPY521ri3772eYVA2zWMiMHLoH0qy76m+N9QIiVBL2cJ7qtCeaCwkoDrfmj5zU9EO+u27PaE2fheJKo/F9ITlo+/Gvd4gIbBUoMsLhLwHN0f4cB76YrAGnewYi3lSaKGwlO24YurAq540mKPJVxRADJTjEFqcv7YanET84+N7wVGWezslFzOzOvTjBjoQJtuNRjflzsbjb5M2hegpN+J0jFm04pCTZv61NNlP9vQqLSp+RkMHotgnyo01NVAy7BkbEFJg1MY9MJ8IrE0DGrGoRI46bsu90Bkkn4RxElWzpgr9LZpJ7OYU4yVg1r6ubnJCmS0JuI811jcrtzUaJBrbiTMi4LgzC9krh4QL5mHO5XkUyFzLmmIDhvgcS1hWOVOF2FmnlPsUV9id/g/B3Q9UlKXxmUwdphPAHOeukLbmWQDv7OI778CffszsKRY2sIYd2M9Lx2M7Q3KB97z0tCvMZWFRvA90Asjz1b2zTtiwoOxncyeBkkX0KnPpDi6bVAGY/9EchAXQvOuhx/J3Xb89gFkOdbyHoOfItlZbj3OJbSAqUrAv2d6JmIE=
    - secure: nYJ8oPJZOUfxe90oSyu4jFSZuk2oyUB89jEkmSFqDPiYfZm9ZhUNbWvodVwAD8d3hMkcIiexQkma9iX+wzjT06IAT1R/dqWrNXMecCSJ42b/KrW4YGz145yKLcdOonsOR9A4UrzOTIwtaQnfrj0gOZdmCKQ1MjDO9pJEtyhqeTjtNGEAJcbAjD+/osOG0aKSbPC4EoBDSUElef7oZ2bv5ZZJldWxoHOuXBLTIdAJO+yAW94i38ytd/Bm58h+RYgR5vx/DvTQ1Zg0QjpONio036Xe/HWTgtWEyWLzJMiXCmX+atk1DajT3FomgWKPaaDv/sQojPsa61RYgttiZ6KGKwWH/LId5XI9b86DXoEcu+oDbiW/CDGEwIjw3lMTyfi+6uGi2cA1QXVPT5e3AJVSmi63fWSaK63N2/qXPmK6mZugC9fg0oc4BOaP4aNhBhHFMIoFjV3KHQ8G1SMrIqIVEJzRIAgYOtFJmLYjRQNNv+EZJMPLUp+xgKEzbhmLivDC4Q8SeYndR9iKLqGVJ2OHHurzJxACP9a5o3TpYvGVpkVLo3Px9A9O7i+yR7Z+K3NPLW9lJ5IOWLzSFJwZcis/ckzIbUsrR6MYKzsKUOmsaYfbTa9WhvWSLI1TVGXuneXQF1/dwLOIwMtypuSR2DvoN/k1ORjFXG+Q7zKKfus4jlM=
    - secure: F8Mm/D6KsJsQ8bofMff/SguZenozWjjBTCL2LgbbCOX2Zaipjj3AOaVtXPv42UrUsJ5mDFFaZA15tLWgJw0yz6ZN6RWfEbbdrMdOj4TR1FFVi5OcALyw3Kw6EFHfkF8xCF0eG/jxhFCsZEMogyXVRCL4GkrmZDwLaa1s0pwQSPGaRzI/GOVcbiQgRZcJo1k+8lw9HGA8alVy/zBNsEOLhvJsEp3lXg9YLVtjwGBNvC2U2Am3Oqm88IIwS3GXX85ANgAgzq+7mkjNXHZd7PvhBg18kVBu098Xo7jRMgfAyD2YPSU6gjavunFQh5sZLd7m9V3tXRYOEKE6+ZCb7UQ6ukjdOB1syp/3d7vEIfTkAicWft8DnWU1hKGfrOJm5GGeNK0wpuCwhzwzvNNIyJ8O90+DxpXrOHdyOxlfWZl9+J6BfG+Rbv/hceaQKHeS0NrfsxiEFJDV13QMajTie/40bKwNYpeFQoZY0StCXwNFfwVdEoAvJMXx/2eraKheovldoQ3lLG6WSeeeBAEu0ToGiCAgeKdaDoS0TjKoXKnWsv296OO6pp131AAAiSCWbMPbg5sTxJNnK48p+yyeQVjbFmEJL7JHREguj3/YnRjlO+1KiX4XM5kytf88z7mYYqcRyuwMqnIT22tA89DxYHpuiP8J+WuG/TcCorb3Lc/NoQc=
addons:
  ssh_known_hosts: ec2-3-124-206-1.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=customer-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-3-124-206-1.eu-central-1.compute.amazonaws.com 'bash launch_build.sh'
  on:
    branch: master
